<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Promise对象</title>
    <style>
        p,
        li {
            font-size: 20px;
            padding: 0 20px;
            line-height: 40px;
        }
    </style>
</head>
<body>
    <h1>Promise对象作用</h1>
    <p>
        Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。它由社区最早提出和实现，ES6 将其写进了语言标准，统一了用法，原生提供了Promise对象。<br> 所谓Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理。
    </p>
    <p>
        Promise对象有以下两个特点。<br> <br> （1）对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。
        <br> <br> （2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。
    </p>
    <h1>基本用法</h1>
    <p>ES6 规定，Promise对象是一个构造函数，用来生成Promise实例。Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。</p>
    <p style="color: #09f009;background: #0f0c0c;">
        var promise = new Promise(function(resolve, reject) {<br> &nbsp;&nbsp; // ... some code<br> &nbsp;&nbsp;&nbsp;&nbsp;if (/* 异步操作成功 */){<br> &nbsp;&nbsp;&nbsp;&nbsp;resolve(value);
        <br> &nbsp;&nbsp;} else {<br> &nbsp;&nbsp;&nbsp;&nbsp;reject(error);
        <br> &nbsp;&nbsp;}
        <br> });
        <br>
    </p>
    <p>resolve函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从 pending 变为 resolved），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；reject函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从 pending 变为 rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。</p>
    <h1>常用方法</h1>
    <h2 style="color: #03a5b2;background: #0f0c0c;">promise.then(resolved,[rejected])</h2>
    <p>then方法是加在Promise构造函数的prototype上的方法，因此对所有Promise实例都可以使用该方法。作用是为 Promise 实例添加状态改变时的回调函数。then方法的第一个参数是resolved状态的回调函数，第二个参数（可选）是rejected状态的回调函数。只有一个参数代表只执行resolved状态的回调函数</p>
    <p style="color: #09f009;background: #0f0c0c;">
        promise.then(function(value){<br> &nbsp;&nbsp;console.log('异步操作成功,结果是' + value)<br> },function(error){
        <br> &nbsp;&nbsp;console.log('异步操作失败,错误是' + error)<br> })
    </p>
    <h2 style="color: #03a5b2;background: #0f0c0c;">promise.catch(rejected)</h2>
    <p>
        用于指定发生错误时的回调函数。相当于promise.then(null,rejected);
    </p>
    <p style="color: #09f009;background: #0f0c0c;">
        promise.then(function(value){<br> &nbsp;&nbsp;console.log('异步操作成功,结果是' + value)<br> }).catch(function(error){
        <br> &nbsp;&nbsp;console.log('异步操作失败,错误是' + error)<br> })
    </p>
    <p>
        需要注意的是，之前提到Promise对象的状态一旦固定就不会发生改变，也就是说new Promise(function(resolve, reject){})中的resolve和reject函数只会执行一个，要么成功，要么失败，如果已经是成功，那么就算再抛出异常也不能被catch捕获到。但是then方法会返回一个新的promise对象，所以如果在then中抛出异常，catch就可以捕获到了。
    </p>
    <p style="color: #09f009;background: #0f0c0c;">
        //案例一<br> let pro1 = new Promise(function(resolve, reject) { <br> &nbsp;&nbsp;resolve('ok');
        <br> &nbsp;&nbsp;reject('error');
        <br> })
        <br> pro1.then(function(value) {<br> &nbsp;&nbsp;console.log(value);
        <br> }).catch(function(error) {<br> &nbsp;&nbsp;console.log(error);
        <br> })<br> //ok
        <br><br> //案例二
        <br> let pro2 = new Promise(function(resolve, reject) { <br> &nbsp;&nbsp;reject('error');
        <br> &nbsp;&nbsp;resolve('ok');
        <br> })
        <br> pro2.then(function(value) {<br> &nbsp;&nbsp;console.log(value);
        <br> }).catch(function(error) {<br> &nbsp;&nbsp;console.log(error);
        <br> })<br> //error
        <br><br> //案例二
        <br> let pro3 = new Promise(function(resolve, reject) { <br> &nbsp;&nbsp;resolve('ok');
        <br> &nbsp;&nbsp;reject('error');
        <br> })
        <br> pro3.then(function(value) {<br> &nbsp;&nbsp;console.log(value);<br>&nbsp;&nbsp;alert(haha);//注：haha是一个未声明的变量，所以这里会报错，将会被catch捕获到
        <br> }).catch(function(error) {<br> &nbsp;&nbsp;console.log(error);
        <br> })<br> //'then'中所抛出的异常
    </p>
    <p>注意下边这种情况：将pro1对象作为参数传递给pro2的resolve函数,此时pro2的状态就又pro1的状态决定。</p>
    <p style="color: #09f009;background: #0f0c0c;">
        let pro1 = new Promise(function(resolve, reject) {<br> &nbsp;&nbsp;let flag = false;<br> &nbsp;&nbsp;if(flag){
        <br> &nbsp;&nbsp;&nbsp;&nbsp;resolve('ok');
        <br> &nbsp;&nbsp;}else{
        <br> &nbsp;&nbsp;&nbsp;&nbsp;reject('error');
        <br> &nbsp;&nbsp;} <br> })
        <br> let pro2 = new Promise(function(resolve, reject) {<br> &nbsp;&nbsp;resolve(pro1);
        <br> })
        <br>
        <br> pro2.then(function(value) {<br> &nbsp;&nbsp;console.log(value);
        <br> }).catch(function(error) {<br> &nbsp;&nbsp;console.log(error);
        <br> })
        <br> //'error'
    </p>
    <h2 style="color: #03a5b2;background: #0f0c0c;">Promise.all([p1,p2,p3])</h2>
    <p>接受一个数组（或有Iterator接口的数据结构）作为参数。如下案例pro1, pro2, pro3都是 Promise 实例,pros的状态由三个promise对象决定，只有三个都是成功状态(resolved)，pros的状态才会是成功(resolved)，只要有一个是失败(rejected)，pros的状态则为失败(rejected)</p>
    <p style="color: #09f009;background: #0f0c0c;">
        let pro1 = new Promise(function(resolve, reject) { <br>
        &nbsp;&nbsp;let flag = true;<br>
        &nbsp;&nbsp;if (flag) {<br>
            &nbsp;&nbsp;&nbsp;&nbsp;resolve('ok');<br>
        &nbsp;&nbsp;} else {<br>
            &nbsp;&nbsp;&nbsp;&nbsp;reject('error');<br>
        &nbsp;&nbsp;}<br>
    })<br>
    let pro2 = new Promise(function(resolve, reject) {<br>
        &nbsp;&nbsp;let flag = true;<br>
        &nbsp;&nbsp;if (flag) {<br>
            &nbsp;&nbsp;&nbsp;&nbsp;resolve('ok');<br>
        &nbsp;&nbsp;} else {<br>
            &nbsp;&nbsp;&nbsp;&nbsp;reject('error');<br>
        &nbsp;&nbsp;}<br>
    })<br>
    let pro3 = new Promise(function(resolve, reject) {<br>
        &nbsp;&nbsp;let flag = true;<br>
        &nbsp;&nbsp;if (flag) {<br>
            &nbsp;&nbsp;&nbsp;&nbsp;resolve('ok');<br>
        &nbsp;&nbsp;} else {<br>
            &nbsp;&nbsp;&nbsp;&nbsp;reject('error');<br>
        &nbsp;&nbsp;}<br>
    })<br>
    // 生成一个Promise对象的数组<br>
    var [...promises] = [pro1, pro2, pro3];<br>
    var pros = Promise.all(promises)<br>
       pros.then(function(value) {<br>
        &nbsp;&nbsp;console.log(value) //value是一个数组，包括pro1, pro2, pro3成功的返回值<br>
    }).catch(function(error) {<br>
        &nbsp;&nbsp;console.log(error)  //error为其中一个promise对象中的异常，或者then中的异常<br>
    });
    </p>
    <h2 style="color: #03a5b2;background: #0f0c0c;">Promise.resolve(),Promise.reject()</h2>
    <p>
        --Promise.resolve():将现有的对象转化为Promise对象，表示成功状态<br>
        --Promise.reject():将现有的对象转化为Promise对象，表示失败状态<br>
    </p>
    <p style="color: #09f009;background: #0f0c0c;">
       /*******Promise.resolve()*******/<br>
        let p = Promise.resolve($.get('json/data.json'));<br>
        //等价于<br>
        let p = new Promise(function(resolve,reject){<br>
            &nbsp;&nbsp;resolve($.get('json/data.json'));<br>
        })<br>
        /*******Promise.reject()*******/<br>
        
        let p = Promise.reject($.get('json/data.json'));<br>
        //等价于<br>
        let p = new Promise(function(resolve,reject){<br>
            &nbsp;&nbsp;reject($.get('json/data.json'));<br>
        })
    </p>
</body>
<script>
    let pro1 = new Promise(function(resolve, reject) {
        let flag = true;
        if (flag) {
            resolve('ok');
        } else {
            reject('error');
        }
    })
    let pro2 = new Promise(function(resolve, reject) {
        let flag = true;
        if (flag) {
            resolve('ok');
        } else {
            reject('error');
        }
    })
    let pro3 = new Promise(function(resolve, reject) {
        let flag = true;
        if (flag) {
            resolve('ok');
        } else {
            reject('error');
        }
    })
    // 生成一个Promise对象的数组
    var [...promises] = [pro1, pro2, pro3];
    Promise.all(promises).then(function(value) {
        console.log(value) //value是一个数组，包括pro1, pro2, pro3成功的返回值
    }).catch(function(error) {
        console.log(error)  //error为其中一个promise对象中的异常，或者then中的异常
    });
</script>
</html>
